config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
root 'pages#landing'
get 'landing' => 'pages#landing'
get 'pages/Sexual_assault1'
get 'pages/Sti'
get 'pages/Sexual_assault1'
  authenticated :user do
   root 'pages#landing', as: :authenticated_root
 end
get 'pages/Prenatal_sweden'
get 'pages/landing'
get 'pages/India_summary'
get 'pages/Sweden_summary'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    def after_sign_in_path_for(resource)
        request.env['omniauth.origin'] || stored_location_for(resource) || root_path
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
	end

	def landing
	end

	def Sexual_assault1
	end
	
	def Conerceptive_Plan_B
	end

   def Prenatal_sweden
	 end

   def India_summary
	 end

	def landing
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header1.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse-ex">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to(image_tag("ovia_logo.png", :size => "60x60", :border => "0"), root_path) %>
    </div>

    <div class="collapse navbar-collapse navbar-collapse-ex" >

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to "Home", landing_path %></li>
        <li><%= link_to "Sexual Assault", pages_Sexual_assault1_url %></li>
        <li><%= link_to "STI", edit_user_registration_path %></li>
        <li><%= link_to "Prenatal", pages_Prenatal_sweden_url %></li>
        <li><%= link_to "Contraceptive", edit_user_registration_path %></li>
        <li><%= link_to "Account", edit_user_registration_path %></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OviaHealthHackathon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class= "container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
      <%= yield %>
      </div>

  </body>
</html>

app/views/pages/India_summary.html.erb
<%= render 'layouts/header1' %>
<h1>Health Care in India </h1>

<p>Zika is a risk in India. Zika infection during pregnancy can cause serious birth defects.
If you engaged in unprotected consensual or forced sexual intercourse, speak with your health-care provider about the risk of Zika.</p>

<p><b>Welcome to Delhi!</b><br/>
Delhi is an exciting and wonderful place but that can also be a difficult city for women to navigate.</p>

<p>In India,  contraceptives are legal and can be purchased without a prescription in pharmacies. If you need contraception, go to the nearest pharmacy and ask for your contraception of choice. Emergency contraception is also sold without a prescription, although some brands may not be available. Because of cultural norms, some women report feeling uncomfortable when seeking such services. Remember, these services are legal and are available in India. Even if you are made to feel intimidated, they are required to provide you with your contraception.</p>
  <p>Pads and tampons are available everywhere, although tampons may not be as available and may come without applicators.  The menstrual cup is more difficult to find.</p>
<p>In India, you can purchase many medications without a prescription from any pharmacy. It is highly recommend that you seek advice from a medical professional before starting any medication.</p>

<p>India has a vast health care system. All government hospitals are required to provide free of cost healthcare facilities to the patients. The government health care system is designed as a three-tier structure comprising primary, secondary, and tertiary facilities. In rural areas, primary health care services are provided through a network of subcenters, primary health centers, and community health centers.India’s private health care sector is not well regulated. Private health care providers deliver an array of outpatient services in solo practices ranging from those not registered with the relevant medical council to trained medical practitioners to small nursing homes and multispecialty clinics. Ask if your is registered.  All government hospitals are required to provide free of cost healthcare facilities to the patients</p>

<p>Sexual assault in India is serious concern.  Delhi is one of the worst places in the world for sexual violence against women,Practice vigilance. Travel in groups, do not walk alone at night, and travel in pairs when using public transportation. Safety apps have also been launched, taxi and rickshaw drivers have received lessons on gender and women’s self-defence classes and women-only taxi services have also sprung up around the city.There were 2,155 rapes recorded in Delhi in 2016 - a rise of 67 per cent from 2012, according to police data. </p>

app/views/pages/Prenatal_sweden.html.erb
<%= render 'layouts/header1' %>
<% provide(:title, "Prenatal_sweden") %>
<!DOCTYPE html>
<html>
<head>
<title>Prenatal Sweden</title>
</head>

<body>



<div>
<h1><b>What to look out for when travelling during the second trimester of your pregnancy.</b></h1>

<p>Generally, the second trimester is the ideal time to travel. However, some possible conditions that can occur during the second trimester:
<ul>
<li>bleeding</li>
<li> preterm contractions</li>
<li> blood clots, especially during long travel</li>
</ul>

<%= content_tag(:iframe,'', width: 400, height: 300, src: "https://www.google.com/maps/embed/v1/search
	?key=AIzaSyBtiB6Lnc8zSXP_vWAbkvusHkncFd52iiw
	&q=medical+centers+in+#{current_user.current_location}") %>

 These may or may not be indicative of a serious medical condition in the pregnancy. <b>If you encounter any of these symptoms before or during travel, please make sure to seek a healthcare provider for assessment</b>

 <br/>In addition, please check with your health care provider before travelling internationally to discuss the safety factors for you and your baby. Before you adventure abroad,<a href="http://americanpregnancy.org/pregnancy-health/traveling-during-pregnancy/  " target="_blank">here</a> here are some helpful items to keep in to mind as you plan your trip.</p>


 </div>


<h1>Contrary to the US, the best providers for maternity care in Sweden are midwives.</h1>

<p>Sweden has a long history of professionally training midwives, who provide the majority of maternity care, which is different from the US. There are many midwife reception centers throughout the country and they also offer STI testing, prescriptions for contraception pills, and pregnancy tests. </p>


<h2>Locations of nearest medical clinics </h2>




</body>
</html>

app/views/pages/Sexual_assault1.html.erb
<%= render 'layouts/header1' %>
<% provide(:title, "Sexual_assault1") %>
<!DOCTYPE html>
<html>

<head>
<title>Summary Women's Health India</title>
</head>

<body>

<div>
<h1> If this is an Emergency, call  112.
If you have experienced sexual assault and have already been to a hospital, call the Delhi’s women helpline:  1091/1092 for information on emotional, mental, and legal support.
 </h1>

 <h2>Locations of nearest medical clinics </h2>

<%= content_tag(:iframe,'', width: 400, height: 300, src: "https://www.google.com/maps/embed/v1/search
	?key=AIzaSyBtiB6Lnc8zSXP_vWAbkvusHkncFd52iiw
	&q=medical+centers+in+#{current_user.current_location}") %>

</div>

<div>
<h1>Seek immediate health and mental service. </h1>

In India, both private and public health professionals are obligated to provide treatment by law.  Denial of treatment of rape survivors is punishable under law. You do not need to file a police report before accessing medical services. Head to the nearest hospital or clinic immediately.

Here is a checklist of what to expect and demand for the health care provider:

<ul>
<li> Health care provide should ask for you informed consent before examination, evidence collection and disclosing information to law enforcement agencies. Consent is mandatory before examination </li>
<li> Health provide will ask for detailed documentation of history of assault, gender sensitive examination, and may collectrelevant forensic evidence </li>
<li> This examination should be free and they should be able to refer you to appropriare mental health services </li>
<li> Health care provider should provide referalsto appropriate agencies for further help like legal support services, shelter services etc. </li>
</ul>

<p>Currently, there is no prepackaged standardized “kit” in India but there are established procedures for clinic examinations for sexual assaults survivors. </p>
<p>If your healthcare provider does not test for STIs, visit a testing center in Delhi. Follow up testing for STI’s should also occur 1-2 months after the assault. For more information on where to seek testing in Delhi, visit <a href="https://www.better2know.in/clinics/city/delhi" target="_blank">Better2Know</a></p>

</div>

<div> <href= Addtional Articles and Resources </div>
<h1><a href="https://www.rainn.org/articles/intimate-partner-sexual-violence" target="_blank">Intimate Partner Sexual Violence </a> </h1>

<p>A perpetrator can have any relationship to a victim, and that includes the role of an intimate partner. There are many different terms to refer to sexual assault committed by a person in a relationship with the victim, including: intimate partner sexual violence, domestic violence, intimate partner rape, marital rape, and spousal rape. No matter what term is used or how the relationship is defined, it is never okay to engage in sexual activity without someone’s consent.</p>

<h1><a href="http://www.pcar.org/about-sexual-violence/women" target="_blank">About Sexual Assault</a> </h1>

<p>Sexual violence is a term meant to include any type of unwanted sexual contact. This can include words and actions of a sexual nature including, but not limited to:
<ul>
<li>Rape</li>
<li>Sexual assault</li>
<li>Incest</li>
<li>Child sexual assault</li>
<li>Date and acquaintance rape </li>
<li>Grabbing or groping </li>
</ul>
</p>



</body>
</html>

app/views/pages/Sweden_summary.html.erb
<%= render 'layouts/header1' %>
<h1>Health Care in Sweden </h1>

<h1>Welcome to Sweden!</h1>
Sweden is wonderful, politically stable country and has a healthcare system that is consistently referenced to as a model system. 
Here are some quick notes to keep in mind if you need medical care while in Sweden.
Without documents, unless you are below 18 years old, you may only be able to receive emergency medical and dental care. If you are sick or need medical care, first call 1177, which is the medical services line, to discuss with a nurse, who can help determine if the inquiry can be resolved over the phone, if you need to go to a health center, or if you need to go to an ER. Health centers are typically the first point of care for most treatments, and generally have less wait times than ERs. Once seen at a health center, you can receive a referral to a specialty clinic such as the maternity clinic for pregnant women or the gynaecologist, who can help assist with sexual and reproductive health inquiries . If there is an emergency, call 112.

<h1>An Overview of the Sweden Healthcare System.</h1>
<p>Healthcare coverage in Sweden is universal, which means all residents, including expatriates, have access to publicly financed healthcare services. This system covers inpatient and outpatient hospital care, prescription drugs, primary healthcare, dental care for children and young people, public health and preventive services, disability support and rehabilitation services. In addition, homecare, nursing home-care, and patient transport support services are also covered under the publicly financed healthcare system. However, contrary to popular belief, healthcare in Sweden isn’t always 100 percent free. Cost-sharing arrangements are available for most publicly financed services.</p>

<h1>How to purchase prescription medicines and other prescription products in Sweden</h1>
<p>Medications can be obtained at Apoteket, which is a state-owned pharmaceutical company and is the largest provider of medications in Sweden. In order for you to pick up prescription drugs at a pharmacy or order them online from apoteket.se a doctor or other prescriber must write a prescription for you.</p>

<h1>How to purchase feminine products in Sweden</h1>
<p>It can be difficult to find tampons for purchase in Sweden, as they are not widely available. Most women switch to using maxi pads. If you are looking to purchase tampons, and you are unable to find them at a local store, they can be purchased online via drugstore.com (America version) and shipped via myUS.com to Sweden. MyUS.com is a shipping service that provides a way for products to be purchased from American stores and shipped abroad.</p>

<h1>If you are having intercourse or have had intercourse, consensual or forced, it is very important to undergo STI testing.</h1>

<p>In Sweden, health centers are typically the first point of care and per law, you are required to undergo STI testing if there is a suspicion of having contracted a sexually transmitted infection. STI testing is free for any individuals and is available through health centers, gynecological clinics, youth centers, and midwife receptions centers. If there are any questions, you can always call 1177 for advice.</p>
 
<h1>How and where can you purchase contraceptives in Sweden?</h1>
<p>The morning-after pill is available over the counter or behind the counter in Sweden and in other parts in Europe. A prescription is required in order to purchase contraceptives everywhere except in the UK. Midwife reception centers in Sweden can provide prescriptions to contraception pills. Levonorgestrel-only emergency contraception pills, which are effective for up to 3 days after intercourse, cost around €17 when bought over the counter at pharmacies, hospitals and family planning clinics. It can be obtained free of charge in various public health centres, particularly youth clinics. Other options include ulipristal acetate emergency contraception pills, which are effective for up to 5 days after intercourse, and an IUD, if it is placed within 5 days after intercourse.</p>

<p>If you have had unprotected intercourse, consensual or forced, to reduce the risk of pregnancy, some emergency measures will be needed. 
Emergency contraception (often called morning-after-pill or Plan B) is a pill that you can take after you have had unprotected intercourse, to reduce the risk of pregnancy. The sooner you take the pill, the less likely you are to get pregnant.</p>


app/views/pages/home.html.erb
<%= render 'layouts/header1' %>

<div class="container">
	<h1>Home</h1>
	<h1>Emergancy<h1>
	 <p>If you have an emgancy please, reach out to the police </p>
 <li><%= link_to " Sexual assult", pages_Sexual_assault1_url %></li>
 <li><%= link_to " Prenatal", pages_Prenatal_sweden %></li>


</div>

app/views/pages/landing.html.erb
<%= render 'layouts/header1' %>
<!DOCTYPE html>
<html>
  <head>
  <title>landing page</title>
  <style>
    .button{
      background: white;
    }
  </style>
  </head>
  <body>
<h1>Welcome to India/ Sweden </h1>
<h2> If this is an <b>Emergency</b> in Sweden please call <a href="tel:+112">112</a> <h2>
<h2> If this is an <b>Emergency</b> in New Delhi please call <a href="tel:+112">102</a><h2>



<button type="button" class="button"><%= link_to " Sexual Assault", pages_Sexual_assault1_url %></a></button>
<button type="button" class="button"><%= link_to " Prenatal", pages_Prenatal_sweden_url %></button>
<button type="button" class="button"><%= link_to " Contraceptive/Plan B", pages_Prenatal_sweden_url %></button>
<button type="button" class="button"><%= link_to " Medications/Feminine products", pages_Prenatal_sweden_url %></button>



    <h2>India- New Delhi</h2>
    <p>Zika is a risk in India. Zika infection during pregnancy can cause serious birth defects. If you engaged in unprotected consensual or forced sexual intercourse, speak with your health-care provider about the risk of Zika.
Welcome to Delhi!
Delhi is an exciting and wonderful place but that can also be a difficult city for women to navigate.
In India,  contraceptives are legal and can be purchased without a prescription in pharmacies.<%= link_to "Read more" , pages_India_summary_url %></p>

<h2>Sweden</h2>

<p>Welcome to Sweden!
Sweden is wonderful, politically stable country and has a healthcare system that is consistently referenced to as a model system.
Here are some quick notes to keep in mind if you need medical care while in Sweden.
Without documents, unless you are below 18 years old, you may only be able to receive emergency medical and dental care. If you are sick or need medical care, first call 1177, which is the medical services line, to discuss with a nurse, who can help determine if the inquiry can be resolved over the phone, if you need to go to a health center, or if you need to go to an ER.<%= link_to  "Read more" , pages_Sweden_summary_url %></p>
</p>



  </body>
</html>